Fix some typing errors reported by mypy (#99)
* server: Fix type definition for **kwargs

As seen on
https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values
only the values of kwargs should be annotated, so using an annotation as
Dict means that the values of must be dict.

In this case, this is a generic decorator, so we can not have more
specific annotation than Any.

* protocol: fix type definition

mypy reported:

    pygls/protocol.py:410: error: Argument 1 of "connection_made" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "BaseTransport"

* protocol: fix a mypy error about format()

mypy reported:

    pygls/protocol.py:416: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior