types: use enum class for enums
Using enums allows more precise type checking. The current code in
types.py was already using *Kind classes as if they were enums, which
mypy reported as type errors:

    pygls/types.py:377: error: Incompatible default for argument "severity" (default has type "int", argument has type "DiagnosticSeverity")
    pygls/types.py:663: error: Incompatible default for argument "trace" (default has type "str", argument has type "Optional[Trace]")

By using enum.IntEnum, enum.IntFlag or subclassing both str and
enum.Enum for string enums, we ensure equality with protocol object
deserialized as simple int or strings.

To keep compatibility with python 3.5 which does not support
enum.IntFlag, WatchKind is not implemented as an enum on python 3.5.